INSERT INTO ROOM (ROOM_ID, NAME, BED_INFO) VALUES(10001,'private room1','semi');
INSERT INTO ROOM (ROOM_ID, NAME, BED_INFO) VALUES(10002,'private room2','semi');
INSERT INTO ROOM (ROOM_ID, NAME, BED_INFO) VALUES(10003,'private room3','semi');
INSERT INTO ROOM (ROOM_ID, NAME, BED_INFO) VALUES(10004,'private room4','semi');
INSERT INTO ROOM (ROOM_ID, NAME, BED_INFO) VALUES(10005,'private room5','semi');