CREATE TABLE ROOM(
ROOM_ID BIGSERIAL PRIMARY KEY,
NAME VARCHAR(16) NOT NULL,
BED_INFO CHAR(10) NOT NULL);

CREATE TABLE EMPLOYEE(
EMPLOYEE_ID CHAR(36) PRIMARY KEY,
FIRST_NAME VARCHAR(64),
LAST_NAME VARCHAR(64),
POSITION VARCHAR(64));